[project]
name = "misaki"
dynamic = ["version"]
description = "G2P engine for TTS"
readme = "README.md"
authors = [
    { name = "hexgrad", email = "hello@hexgrad.com" }
]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.11, <3.15"
dependencies = [
    "regex>=2026.5",
]

[project.optional-dependencies]
en = ["numpy", "num2words", "spacy<4"]

en-fallback = ["torch", "transformers"]

espeak = ["phonemizer-fork", "espeakng-loader"]

ja = [
    "fugashi[unidic-lite]",
    "jaconv",
    "mojimoji",
    "pyopenjtalk",
]

ko = [
    "jamo",
    "python-mecab-ko",
]

zh = ["jieba", "ordered-set", "pypinyin", "cn2an", "pypinyin-dict"]

multilingual = [
    "numpy",
    "num2words",
    "spacy<4",
    "fugashi[unidic-lite]",
    "jaconv",
    "mojimoji",
    "jamo",
    "python-mecab-ko",
    "jieba",
    "pypinyin",
    "cn2an",
    "pypinyin-dict",
]

ui = [
    "gradio>=6.19.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "misaki/__init__.py"

[dependency-groups]
en-sm = [
    "en-core-web-sm==3.8.0",
]
en-trf = [
    "en-core-web-trf==3.8.0",
]
dev = [
    "basedpyright>=1.39.9",
    "black>=24.8.0",
    "isort>=5.13.2",
    "pytest>=8.3.5",
    "ruff>=0.15.20",
]

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
en-core-web-trf = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.8.0/en_core_web_trf-3.8.0-py3-none-any.whl" }
